### ISSUE TITLE
@synthesize backgroundImage;

### ISSUE THREAD

**Issue by ghost** [onemightyroar/YRDropdownView#4]
@synthesize backgroundImage; 

Error:

//Existing ivar 'BackgroundImage' for unsafe_unretained propert 'backgroundImages' must be __unsafe_unretained.

@synthesize accessoryImage;

Error:
 //Existing ivar 'accessoryImage' for unsafe_unretained property 'AccessoryImage' must ben __unsafe_unretained

iOS5

**Comment by eliperkins** [comment]
Are you sure you've disabled ARC on these files? This seems like something that might be thrown by this. See the readme to learn how to do this.
